// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/Board.tsx";
import * as $$1 from "./islands/Conclusion.tsx";
import * as $$2 from "./islands/Game.tsx";
import * as $$3 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/Board.tsx": $$0,
    "./islands/Conclusion.tsx": $$1,
    "./islands/Game.tsx": $$2,
    "./islands/Search.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
